name: wca-rag
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pyyaml
  - pytorch
  - sentence-transformers
  - ipython
  - tqdm
  - seaborn
  - pip
  - pip:
      - python-dotenv
      - google-genai
      - groq